name: Deploy to devnet

inputs:
  rpc:
    description: 'rpc'
    required: true
    type: string
  pid:
    description: 'program PID'
    required: true
    type: string
  pid_env_var:
    description: 'program PID env var'
    required: true
    type: string
  program_name:
    description: 'program name'
    required: true
    type: string
  kp:
    description: 'Deploy KP'
    required: true
    type: string
  ssh_private_key:
    description: 'SSH private key'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup program
      uses: bridgesplit/anchor-setup-gh-action@v1.0.7
      with:
        ssh_private_key: ${{ inputs.ssh_private_key }}
        rpc: ${{ inputs.rpc }}
        pid: ${{ inputs.pid }}
        pid_env_var: ${{ inputs.pid_env_var }}

    - name: Deploy program
      run: |
        echo "${{ inputs.kp }}" > solana-keypair.json
        solana program deploy --keypair solana-keypair.json target/deploy/${{ inputs.program_name }}.so --program-id ${{ inputs.pid }} -u ${{ inputs.rpc }}
      shell: bash
